name: Cypress Testing Workshop pipeline

on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Testing
        run: npm run e2e:full

      - name: Upload the testing results
        uses: actions/upload-artifact@v4
        with:
          path: cypress/results
